/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __nad_lcm_block_info_hpp__
#define __nad_lcm_block_info_hpp__

#include <string>

namespace nad_lcm
{

/// 施工标志描述结构
class block_info
{
    public:
        std::string block_id;

        std::string block_type;

        int32_t    block_value;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "block_info"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int block_info::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int block_info::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int block_info::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t block_info::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* block_info::getTypeName()
{
    return "block_info";
}

int block_info::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* block_id_cstr = (char*) this->block_id.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &block_id_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* block_type_cstr = (char*) this->block_type.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &block_type_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->block_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int block_info::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __block_id_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__block_id_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__block_id_len__ > maxlen - pos) return -1;
    this->block_id.assign(((const char*)buf) + offset + pos, __block_id_len__ - 1);
    pos += __block_id_len__;

    int32_t __block_type_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__block_type_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__block_type_len__ > maxlen - pos) return -1;
    this->block_type.assign(((const char*)buf) + offset + pos, __block_type_len__ - 1);
    pos += __block_type_len__;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->block_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int block_info::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->block_id.size() + 4 + 1;
    enc_size += this->block_type.size() + 4 + 1;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

int64_t block_info::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0xb198915db8d9b613LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
