/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __nad_lcm_cu_config_respond_hpp__
#define __nad_lcm_cu_config_respond_hpp__

#include <string>
#include <vector>
#include "obu_config.hpp"
#include "rsu_config.hpp"
#include "task_config.hpp"

namespace nad_lcm
{

/// csu->oct：返回基本配置
class cu_config_respond
{
    public:
        std::string csu_name;

        std::string csu_type;

        int16_t    num_of_obu;

        std::vector< nad_lcm::obu_config > obu;

        int16_t    num_of_rsu;

        std::vector< nad_lcm::rsu_config > rsu;

        int16_t    num_of_task;

        std::vector< nad_lcm::task_config > task;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "cu_config_respond"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int cu_config_respond::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int cu_config_respond::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int cu_config_respond::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t cu_config_respond::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* cu_config_respond::getTypeName()
{
    return "cu_config_respond";
}

int cu_config_respond::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* csu_name_cstr = (char*) this->csu_name.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &csu_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* csu_type_cstr = (char*) this->csu_type.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &csu_type_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_obu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_obu; a0++) {
        tlen = this->obu[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_rsu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_rsu; a0++) {
        tlen = this->rsu[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_task, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_task; a0++) {
        tlen = this->task[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int cu_config_respond::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __csu_name_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__csu_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__csu_name_len__ > maxlen - pos) return -1;
    this->csu_name.assign(((const char*)buf) + offset + pos, __csu_name_len__ - 1);
    pos += __csu_name_len__;

    int32_t __csu_type_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__csu_type_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__csu_type_len__ > maxlen - pos) return -1;
    this->csu_type.assign(((const char*)buf) + offset + pos, __csu_type_len__ - 1);
    pos += __csu_type_len__;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_obu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->obu.resize(this->num_of_obu);
    for (int a0 = 0; a0 < this->num_of_obu; a0++) {
        tlen = this->obu[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_rsu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->rsu.resize(this->num_of_rsu);
    for (int a0 = 0; a0 < this->num_of_rsu; a0++) {
        tlen = this->rsu[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_task, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->task.resize(this->num_of_task);
    for (int a0 = 0; a0 < this->num_of_task; a0++) {
        tlen = this->task[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int cu_config_respond::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->csu_name.size() + 4 + 1;
    enc_size += this->csu_type.size() + 4 + 1;
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_obu; a0++) {
        enc_size += this->obu[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_rsu; a0++) {
        enc_size += this->rsu[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_task; a0++) {
        enc_size += this->task[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

int64_t cu_config_respond::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == cu_config_respond::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)cu_config_respond::getHash };

    int64_t hash = 0x86f89011a2385c83LL +
         nad_lcm::obu_config::_computeHash(&cp) +
         nad_lcm::rsu_config::_computeHash(&cp) +
         nad_lcm::task_config::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
