/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __nad_lcm_ou_log_report_hpp__
#define __nad_lcm_ou_log_report_hpp__

#include <string>

namespace nad_lcm
{

/**
 * -------------------------------------------------------------------
 * vui的日志告警接口
 * -------------------------------------------------------------------
 * obu->vui：上报日志
 */
class ou_log_report
{
    public:
        std::string log_proc;

        std::string log_time;

        int32_t    log_level;

        std::string log;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ou_log_report"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int ou_log_report::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int ou_log_report::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ou_log_report::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ou_log_report::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ou_log_report::getTypeName()
{
    return "ou_log_report";
}

int ou_log_report::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* log_proc_cstr = (char*) this->log_proc.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &log_proc_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* log_time_cstr = (char*) this->log_time.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &log_time_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->log_level, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* log_cstr = (char*) this->log.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &log_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int ou_log_report::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __log_proc_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__log_proc_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__log_proc_len__ > maxlen - pos) return -1;
    this->log_proc.assign(((const char*)buf) + offset + pos, __log_proc_len__ - 1);
    pos += __log_proc_len__;

    int32_t __log_time_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__log_time_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__log_time_len__ > maxlen - pos) return -1;
    this->log_time.assign(((const char*)buf) + offset + pos, __log_time_len__ - 1);
    pos += __log_time_len__;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->log_level, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __log_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__log_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__log_len__ > maxlen - pos) return -1;
    this->log.assign(((const char*)buf) + offset + pos, __log_len__ - 1);
    pos += __log_len__;

    return pos;
}

int ou_log_report::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->log_proc.size() + 4 + 1;
    enc_size += this->log_time.size() + 4 + 1;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->log.size() + 4 + 1;
    return enc_size;
}

int64_t ou_log_report::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0x7fa2ca1a37133307LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
