/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __nad_lcm_rsu_info_hpp__
#define __nad_lcm_rsu_info_hpp__

#include <string>
#include <vector>
#include "obu_info.hpp"

namespace nad_lcm
{

/// rsu每秒上报自身信息的结构
class rsu_info
{
    public:
        std::string rsu_name;

        int16_t    num_of_obu;

        std::vector< nad_lcm::obu_info > obu;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "rsu_info"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int rsu_info::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int rsu_info::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int rsu_info::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t rsu_info::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* rsu_info::getTypeName()
{
    return "rsu_info";
}

int rsu_info::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* rsu_name_cstr = (char*) this->rsu_name.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &rsu_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_obu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_obu; a0++) {
        tlen = this->obu[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int rsu_info::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __rsu_name_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__rsu_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__rsu_name_len__ > maxlen - pos) return -1;
    this->rsu_name.assign(((const char*)buf) + offset + pos, __rsu_name_len__ - 1);
    pos += __rsu_name_len__;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_obu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->obu.resize(this->num_of_obu);
    for (int a0 = 0; a0 < this->num_of_obu; a0++) {
        tlen = this->obu[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int rsu_info::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->rsu_name.size() + 4 + 1;
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_obu; a0++) {
        enc_size += this->obu[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

int64_t rsu_info::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == rsu_info::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)rsu_info::getHash };

    int64_t hash = 0x8a4fef052b899770LL +
         nad_lcm::obu_info::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
