/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __nad_lcm_uc_exec_task_request_hpp__
#define __nad_lcm_uc_exec_task_request_hpp__

#include <string>

namespace nad_lcm
{

/**
 * -------------------------------------------------------------------
 * oct执行脚本的接口
 * 脚本实际在csu_scene执行，脚本函数大部分在csu_planning执行
 * 一期的脚本都是一次性执行完，没有“正在执行脚本”的状态
 * -------------------------------------------------------------------
 * oct->csu：请求执行脚本
 */
class uc_exec_task_request
{
    public:
        std::string csu_name;

        std::string task_name;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "uc_exec_task_request"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int uc_exec_task_request::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int uc_exec_task_request::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int uc_exec_task_request::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t uc_exec_task_request::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* uc_exec_task_request::getTypeName()
{
    return "uc_exec_task_request";
}

int uc_exec_task_request::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* csu_name_cstr = (char*) this->csu_name.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &csu_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* task_name_cstr = (char*) this->task_name.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &task_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int uc_exec_task_request::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __csu_name_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__csu_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__csu_name_len__ > maxlen - pos) return -1;
    this->csu_name.assign(((const char*)buf) + offset + pos, __csu_name_len__ - 1);
    pos += __csu_name_len__;

    int32_t __task_name_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__task_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__task_name_len__ > maxlen - pos) return -1;
    this->task_name.assign(((const char*)buf) + offset + pos, __task_name_len__ - 1);
    pos += __task_name_len__;

    return pos;
}

int uc_exec_task_request::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->csu_name.size() + 4 + 1;
    enc_size += this->task_name.size() + 4 + 1;
    return enc_size;
}

int64_t uc_exec_task_request::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0xc48b4b6a3522ffcaLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
